name: Github Actions Demo
on: 
  workflow_dispatch:
  schedule:
    - cron: "15 6 * * 0"
  push:
    branches: 
      - main
    paths-ignore: 
      - .github/**

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: "Print variables"
        shell: python
        run: |
          import os
          print(os.getenv("GITHUB_EVENT_NAME"))
          print(os.getenv("GITHUB_REF"))
      
      - uses: actions/checkout@main

      - name: "list"
        shell: bash
        run: tree
        
      
